### ISSUE TITLE
DMS metric reproduction

### ISSUE THREAD

**Issue by JinyuanSun** [Shunsuke-1994/rfamgen#2]
Hi, can you share the models and data labels used for making predictions of DMS datasets?

**Comment by Shunsuke-1994** [comment]
Hi, I am on holiday today.
I will contact again later!

Shunsuke

**Comment by Shunsuke-1994** [comment]
Resolved by email.
Let me close.

**Comment by Chiyasa** [comment]
Hi, I also want the data used for DMS metric reproduction. Cound u please share?

**Comment by Shunsuke-1994** [comment]
Thank you for your interest. Here it is.
Here it is. `log_rfamgen/*.txt` contains list of elbo values of sequences in `activities/*fa`. The orders of the sequence and the values are same.

https://drive.google.com/drive/folders/1VrVHScCZ1lzqp8FZ1uS9zjOw8uKW-lgy?usp=drive_link

Three datasets are vailable on the following websites:
- Twister ribozyme: [Data (yokobayashilab.net)](https://yokobayashilab.net/data)
- glmS ribozyme: dataframe1 of [Comprehensive sequence-to-function mapping of cofactor-dependent RNA catalysis in the glmS ribozyme | Nature Communications](https://www.nature.com/articles/s41467-020-15540-1#MOESM3)  
- drz-Agam-2 ribozyme: https://pubs.acs.org/doi/suppl/10.1021/acssynbio.7b00367/suppl_file/sb7b00367_si_001.xlsx

The deep mutational scan or tRNA is not available and I am not sure if I have permission of second distribution of the published data. I requested the data to the author and obtained them. 

Best,
Shunsuke

**Comment by Chiyasa** [comment]
> Thank you for your interest. Here it is: https://drive.google.com/drive/folders/1VrVHScCZ1lzqp8FZ1uS9zjOw8uKW-lgy?usp=drive_link `log_rfamgen/*.txt` contains list of elbo values of sequences in `activities/*fa`. The orders of the sequence and the values are same.
> 
> Three datasets are available on the following websites:
> 
> * Twister ribozyme: [Data (yokobayashilab.net)](https://yokobayashilab.net/data)
> * glmS ribozyme: dataframe1 of [Comprehensive sequence-to-function mapping of cofactor-dependent RNA catalysis in the glmS ribozyme | Nature Communications](https://www.nature.com/articles/s41467-020-15540-1#MOESM3)
> * drz-Agam-2 ribozyme: https://pubs.acs.org/doi/suppl/10.1021/acssynbio.7b00367/suppl_file/sb7b00367_si_001.xlsx
> 
> Because the deep mutational scan of tRNA is not open, I requested the data to the author of [this paper](https://www.science.org/doi/10.1126/science.aae0568) and obtained them. I am not sure if I have permission of second distribution of the published data.
> 
> Best, Shunsuke

Thanks for your reply! I have one more question: I downloaded the dataframe listed below
```
* glmS ribozyme: dataframe1 of [Comprehensive sequence-to-function mapping of cofactor-dependent RNA catalysis in the glmS ribozyme | Nature Communications](https://www.nature.com/articles/s41467-020-15540-1#MOESM3)
```
and find that it records many different types of kinetic parameters: kcat, kobs, kM... Which kinetic parameter is used by RfamGen DMS metric calculation? 

Another thing is that, I found the the deep mutational scanning data of tRNA in the [Supplementary Table 2](https://static-content.springer.com/esm/art%3A10.1038%2Fnbt.3769/MediaObjects/41587_2017_BFnbt3769_MOESM13_ESM.xlsx) of https://www.nature.com/articles/nbt.3769, the paper of EVmutation. It might be publicly accessible.

**Comment by Chiyasa** [comment]
Thanks! I have no questions now!
