### ISSUE TITLE
sigma vs variance

### ISSUE THREAD

**Issue by 3f6a** [Shunsuke-1994/rfamgen#3]
In this line:

https://github.com/Shunsuke-1994/rfamgen/blob/b3717ff287e6da46d4167633dd40af07c3caca26/src/models/CMVAE.py#L90

shouldn't it just be `eps * sigma` ?

**Comment by Shunsuke-1994** [comment]
Thank you for pointing out. 
I checked the code immediately, and I found this opened version (and test code of `src/decode.py`) seemed to come from a code branched at a very initial research stage.

I quickly update it to correct version. 
Thank you very much.
